### ISSUE TITLE
ctd upon loading due to severe incompatibility(obsolete version)

### ISSUE THREAD

**Issue by randogaming6252** [alexguirre/gtav-CWeaponInfoBlob-Adjuster#1]
this current version of WeaponLimitsAdjuster is two years outdated and now causes near instant crashes upon loading the game. this mod and three others have effectively killed off about 95% of all vehicle and weapons mods out there to date. only one has been heard of even being tried to be updated and that was heap adjuster. there have been 6-7 updates since this mods last update and is a core dependency for millions of mods.

**Comment by randogaming6252** [comment]
the current config shows these base values, along with name changes:
 ```
<ConfigModelInfo>
                    <defaultPlayerName>player_zero</defaultPlayerName>
                    <defaultProloguePlayerName>csb_prolsec</defaultProloguePlayerName>
                    <MaxBaseModelInfos value="2"/>
                    <MaxCompEntityModelInfos value="100"/>
                    <MaxMloInstances value="18000"/>
                    <MaxMloModelInfos value="220"/>
                    <MaxPedModelInfos value="725"/>
                    <MaxTimeModelInfos value="1800"/>
                    <MaxVehicleModelInfos value="320"/>
                    <MaxWeaponModelInfos value="115"/>
                    <MaxExtraPedModelInfos value="390"/>
                    <MaxExtraVehicleModelInfos value="580"/>
                    <MaxExtraWeaponModelInfos value="610"/>
                </ConfigModelInfo>
```
and 
```
<Item>
                            <PoolName>CWeapon</PoolName>
                            <PoolSize value="1024"/>
                        </Item>
```

the base code of this mod is looking for cweaponinfoblob and it nolonger exists with that name. and the base value is nolonger 512

**Comment by alexguirre** [comment]
This patch still works in the latest version. If you are crashing, it is for some other reason.

CWeaponInfoBlob and CWeapon are two different things. The size of CWeaponInfoBlob is hardcoded in the .exe, it doesn't appear in the gameconfig, and its base value in the latest version is 150.

Similarly for CWeaponComponentInfo, its base value is 470.

**Comment by randogaming6252** [comment]
just about everyone has been crashing since the last three updates. there been major problems with the core 4 crashing. have you not seen the issues that have been being reported on 5mods?

**Comment by alexguirre** [comment]
I have also seen people using it just fine and myself testing it. So unless you have some minimal installation with just my .asi and weapon mods installed I can try to reproduce, not much I can do.
